data: ${PWD}/examples/data

pipeline:
  image: clams-pipeline:0.2.1
  container: pipeline

services:
  - tokenizer:
      image: clams-fastpunct:0.0.5
      container: pipeline_fastpunct
  - spacy:
      image: clams-spacy-nlp:0.0.7
      container: pipeline_spacy
      parameters:
        pretty: True
