data: ${PWD}/examples/data

pipeline:
  image: clams-pipeline:0.1.2
  container: pipeline

services:
  - ina:
      image: clams-ina-segmenter
      container: pipeline_ina
  - kaldi:
      image: clams-kaldi
      container: pipeline_kaldi
  - spacy:
      image: clams-spacy-nlp:0.0.8
      container: pipeline_spacy
      parameters:
        pretty: True
