data: ${PWD}/examples/data

pipeline:
  image: clams-pipeline
  container: pipeline

services:
  - ina:
      image: clams-ina-segmenter
      container: pipeline_ina
  - kaldi:
      image: clams-kaldi
      container: pipeline_kaldi
  - spacy:
      image: clams-spacy-nlp:0.0.7
      container: pipeline_spacy
