data: ${PWD}/examples/data

pipeline:
  image: clams-pipeline
  container: pipeline

services:
  - spacy:
      image: clams-spacy-nlp:0.0.7
      container: pipeline_spacy
      parameters:
        pretty: True
