data: ${PWD}/examples/data

pipeline:
  image: clams-pipeline:0.1.2
  container: pipeline

services:
  - spacy:
      image: clams-spacy-nlp:0.0.8
      container: pipeline_spacy
      parameters:
        pretty: True
