data: ${PWD}/examples/data

pipeline:
  image: clams-pipeline
  container: pipeline

services:
  - tokenizer:
      image: clams-nlp-example
      container: pipeline_tokenizer
  - spacy:
      image: clams-spacy-nlp:0.0.6
      container: pipeline_spacy
