data: ${PWD}/examples/data

pipeline:
  image: clams-pipeline
  container: pipeline

services:
  - tokenizer:
      image: clams-nlp-example:0.0.5
      container: pipeline_tokenizer
  - spacy:
      image: clams-spacy-nlp:0.0.7
      container: pipeline_spacy
